version: "3"

tasks:
  dev:
    cmds:
      - npm run dev

  build:
    cmds:
      - npm run build

  test:
    cmds:
      - npm run test

  lint:
    cmds:
      - npm run lint
    
  start:
    cmds:
      - npm run build && npm run start