version: '3'

tasks:

  dev:
    cmds:
      - cargo run -p sandbox

  build:
    cmds:
      - cargo build -p sandbox

  test:
    cmds:
      - cargo test -p sandbox

  lint:
    cmds:
      - cargo fmt

  start:
    cmds:
      - cargo run --release