version: '3'

tasks:

  dev:
    cmds:
      - go run ./cmd/server

  build:
    cmds:
      - go build -o bin/server ./cmd/server

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - golangci-lint run --fix
  
  start:
    cmds:
      - go build -o bin/server ./cmd/server && ./bin/server

  swagger:
      desc: Generate swagger docs
      cmds:
        - swag init -g cmd/server/main.go -o docs/

  migrate:
      desc: Create migration file, ex, task create-migration NAME=add_access_token
      cmds:
        - goose -dir ./sql/migrations create {{.NAME}} sql
      
  migrate-db:
      desc: make changes in the database with latest migration
      cmds:
        - goose -dir ./sql/migrations postgres "{{.DB_URL}}" up

  generate:
      desc: Generate sql query in go application
      cmds:
        - sqlc generate