basePath: /
definitions:
  apierr.ErrorCode:
    enum:
    - BAD_REQUEST
    - UNAUTHORIZED
    - FORBIDDEN
    - NOT_FOUND
    - CONFLICT
    - UNPROCESSABLE_ENTITY
    - TOO_MANY_REQUESTS
    - INTERNAL_SERVER_ERROR
    - SERVICE_UNAVAILABLE
    type: string
    x-enum-varnames:
    - CodeBadRequest
    - CodeUnauthorized
    - CodeForbidden
    - CodeNotFound
    - CodeConflict
    - CodeUnprocessableEntity
    - CodeTooManyRequests
    - CodeInternal
    - CodeServiceUnavailable
  apierr.FieldError:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  errormiddleware.ErrorResponse:
    description: Standard error response.
    properties:
      code:
        $ref: '#/definitions/apierr.ErrorCode'
      details:
        items:
          $ref: '#/definitions/apierr.FieldError'
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8000
info:
  contact: {}
  description: API documentation
  title: Server
  version: "2.0"
paths:
  /auth/github:
    get:
      consumes:
      - application/json
      description: Redirect to github oauth page
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errormiddleware.ErrorResponse'
      summary: RedirectGithub
      tags:
      - Auth
  /auth/github/callback:
    get:
      consumes:
      - application/json
      description: Verify github code
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Verify github code
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
